### PR TITLE
Added (...) to get.pull.request.commits

### PR DESCRIPTION
**Pull request by aronlindberg**
This is my first pull request ever to a project, so please be gentle.
=) Any feedback will be helpful. I also see that I use a more recent
version of Roxygen, which caused commits in all the other Rdocs (just
updating the version number). Do you want those commits too?

### CODE REVIEW

**Comment by aronlindberg** [comment]
Any thought on whether this can be merged or not?

**Comment by cscheid** [comment]
Sorry about the lack of updates, I'm buried under a bunch of time-sensitive work and can't get to it for the next few days.

**Comment by aronlindberg** [comment]
Bump! =)

**Comment by cscheid** [comment]
Thanks for reminding me. I’ve added to my current todo list, so there :)

**Comment by cscheid** [comment]
Hi, just to let you know I got one big item off of my todo list, and I hope to get to this by the end of the week.

**Comment by cscheid** [comment]
Hey, this looks good but, just to confirm: the reason we need `...` here is pagination parameters, right? Is there anything else?

(I'm considering a more substantial refactoring of the library as @jennybc has suggested in the past, so I'm now collecting all inconsistencies that we can spot.)

**Pull request merged**
